# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

#将favicon放置于source路径根目录
favicon: /favicon.ico

#引入自定义字体资源
font:
  enable: true
  #fonts.googleapis.com (Default)
  host:
  families: Lato:300

#站点作者相关信息
author:
  img: img/author.jpg
  email: zhenghe39@gmail.com
  github: samuerio

#多说评论账户配置
duoshuo_shortname: issUn


excerpt_link: Read More

# Code Highlight theme
# Available value:
#    normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: normal

